services:
  db:
    image: postgres:15
    container_name: subscriptions_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: subscriptions_app
    environment:
      DATABASE_DSN: postgres://user:password@db:5432/subscriptions?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"
    # volumes:
    #   - .:/app  # <--- отключено

volumes:
  postgres_data:
